name: Go Test
on:
  schedule:
    - cron: '17 15 20 8 *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.22.0"

    - name: Check out code
      uses: actions/checkout@v3

    - name: Run tests
      run: go test ./... -timeout=20m
    