name: Go Test
on: [push]

on:
  schedule:
    # Runs at 9:49 AM on August 20th
    - cron: "49 9 20 8 *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.22.0"

    - name: Check out code
      uses: actions/checkout@v3

    - name: Run tests
      run: go test ./... -timeout=20m
    