name: Go Test
on:
  push:
  schedule:
    # Runs at 2:49 PM UTC (9:49 AM COT) on August 20th
    - cron: "58 14 20 8 *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.22.0"

    - name: Check out code
      uses: actions/checkout@v3

    - name: Run tests
      run: go test ./... -timeout=20m
    